name: riverpod_shared_preferences_firebase_starter
description: "A starter project for a Firebase Authentication app. 
              Utilizes Riverpod for state management and Shared Preferences to retain 
              the previously used theme settings."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  firebase_auth: ^4.18.0
  firebase_core: ^2.27.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
